version: '3'
volumes:
    dados:
networks:
    banco:
    web:
    fila:
services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - dados:/var/lib/postgresql/data
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - banco 
    frontend:
        image: nginx:1.13
        volumes:
            #Site
            - ./web:/usr/share/nginx/html/
        ports:
            - 8080:80
        networks:
            - web 
        depends_on:
            - app
    app: 
        image: python:3.6
        volumes: 
            #Aplicação
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        ports: 
            - 8010:8010
        networks:
            - banco
            - web
            - fila
        depends_on:
            - db
            - queue
        environment:
            - DB_NAME=abc_sender
    queue:
        image: redis:3.2
        networks:
            -   fila
    worker:
        build: worker
        volumes: 
            #Workers
            - ./worker:/worker
        working_dir: /worker
        command: worker.py
        networks: 
            - fila
        depends_on:
            - queue
